version = 0.1
[default.deploy.parameters]
stack_name = "Exam-1"
resolve_s3 = true
s3_prefix = "Exam-1"
region = "eu-west-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
