name: Build and Publish Docker Image

on:
  push:
    branches:
      - main  # Trigger workflow på push til main-branchen

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
    # Trinn 1: Sjekk ut repository-koden
    - name: Checkout code
      uses: actions/checkout@v3

    # Trinn 2: Sett opp Docker Buildx for optimal byggeprosess
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Trinn 3: Logg inn på Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Trinn 4: Bygg og Push Docker Image
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/java-sqs-client:latest
